tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "prales": {
                    '50': '#f5f6ef',
                    '100': '#e9ecdb',
                    '200': '#d4dbbb',
                    '300': '#b8c393',
                    '400': '#9dac6f',
                    '500': '#7f9052',
                    '600': '#63723e',
                    '700': '#4d5833',
                    '800': '#434c2f',
                    '900': '#373e29',
                    '950': '#1c2112',
                },
                'gold': {
                    '50': '#fdfbe9',
                    '100': '#fbf7c6',
                    '200': '#f9ed8f',
                    '300': '#f5db4f',
                    '400': '#f0c71f',
                    '500': '#e0af12',
                    '600': '#bb830c',
                    '700': '#9a610e',
                    '800': '#804d13',
                    '900': '#6d3f16',
                    '950': '#3f2109',
                },
                "surface": "#E9EBE5",
                "on-background": "#1d1a22",
                "primary-container": "#336633",
                "secondary": "#bc0000",
                "on-error": "#ffffff",
                "outline": "#72796e",
                "error": "#ba1a1a",
                "primary-fixed-dim": "#9cd596",
                "outline-variant": "#c1c9bc",
                "on-secondary": "#ffffff",
                "on-surface": "#1d1a22",
                "surface-container": "#f3ebf7",
                "surface-container-lowest": "#ffffff",
                "primary-fixed": "#628924",
                "background": "#E9EBE5",
                "surface-container-low": "#fafbf8",
                "surface-container-low": "white",
                "on-surface-variant": "#41493f",
                "on-primary": "#ffffff",
                "surface-container-high": "#d9e6a4",
                "primary": "#373e29",
                "on-primary-fixed": "white",
                "surface-tint": "#366936",
                "button": "#33a2cc",
            },
            fontFamily: {
                "serif": ["Noto Serif"],
                "headline": ["Noto Serif"],
                "body": ["Inter"],
                "label": ["Work Sans"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
        },
    },
}